schema: graphql/schema.graphql
documents:
  - graphql/!(schema).graphql
  - main.go
extensions:
  codegen:
    generates:
      pkg/graphql/graphql.go:
        hooks:
          afterOneFileWrite: go fmt
        plugins:
          - dist/index.js:
              # packageName: graphql # default
