projects:
  default:
    schema: examples/graphql/schema.graphql
    documents: examples/graphql/!(schema).graphql
    extensions:
      codegen:
        generates:
          examples/graphql/graphql.go:
            hooks:
              afterOneFileWrite: go fmt
            plugins:
              - packages/graphql-codegen-golang/dist/index.js:
                  generateHTTPClient: false
  rickandmorty:
    schema: https://rickandmortyapi.com/graphql/
    documents: examples/rickandmorty/document.graphql
    extensions:
      codegen:
        generates:
          examples/rickandmorty/graphql.go:
            hooks:
              afterOneFileWrite: go fmt
            plugins:
              - packages/graphql-codegen-golang/dist/index.js:
                  packageName: rickandmorty
